### PR TITLE
Attempt to factor out cast_to_layout_compatible

### PR DESCRIPTION
**Pull request by cbeck88**
Hi,

Here's my attempt at implementing the idea I described in issue #12 

I had some issues testing it -- even without my commit, I am on ubuntu 16.04 xenial and I don't have a c++14 standard library on my system, so I don't have some things like `std::less<void>` and `std::greater<void>` which are used in some of the tests.

However, the same set of tests are passing and failing before and after my commit, using gcc 5.4 and clang 4.0, nor do I have new warnings. So I think this commit is at least close to correct.

(As a minor complaint -- it would be nice if there were a simple script to run the tests. To figure out how to run them locally I had to sort of reverse engineer from the travis.yml file. I guess that the test mechanism relies on the boost repo and so can't be run without cloning boost.)

I would like to test also on my macbook, and I would also like to do some tests with godbolt to inspect the generated assembly and make sure this is not significantly different in terms of efficiency.

However, I don't have time to do that stuff until about Thursday, so you might want to hold off until then. I will try to test it with c++14 conforming standard library at that time.

---

The commit message describes the changes I made. Basically, where previously we used `cast_to_layout_compatible` and then `make_tuple_of_references`, what I tried to do was, generalize `make_tuple_of_references` so that it takes instead an arbitrary object, together with a `getter` that can implement `get<i>` on that object.

Then, for cases when you needed to apply this to a tuple, there is a `sequence_tuple_getter` which wraps `sequence_tuple::get`. And for user-defined structures, there is an `offset_based_getter`, which takes as template parameters the user-structure `S`, and the `sequence_tuple<T1, T2, ...>` generated by using the ubiqs. Assuming that the `sequence_tuple` is indeed layout compatible with `S`, the `offset_based_getter` I believe should optimize to code that is just as good as `cast_to_layout_compatible`, and I don't think it should violate the standard anywhere. There is some more technical discussion in the commit message.

---

Another thing to be considered, now that I think of it, is that maybe the `cast_to_layout_compatible` should be kept around and enabled by use of a flag -- that way if on some compilers this change causes a regression, people can revert to the old way.

Cheers,
Chris

### CODE REVIEW

**Comment by cbeck88** [comment]
Comment: I played around with some sample code on godbolt to see how well this technique optimizes. It seems to get totally optimized by gcc 4.9 and clang 3.5, but on MSVC I couldn't get it to compile, and ICC didn't optimize it fully. I will have to investigate msvc issues later when I come back to this. Here's my code sample, based on your `sequence_tuple` and my `offset_based_getter`: [godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSBnVAV2OUxAHIBSAJgGY8AO2QAbZlgDU3fgGECATwAOmAPoFiAQ0IMZ2bgAYAgn0EjxUmfOZLRmPYZMDhYiZmlzmBPKMIKHxqYuFu5WALaYYST%2B/PqBxkKaEQxKmuySDJgAjsyYImoENnbSAOwAQo6OBJG2mtUesgwE6CAgDHgAXgWSAHKkkmKaDAySACoBRk3EzMgEkgBGQ2oAZsSoYaoRYfOYxKUVxpJHY5IAbpri9vwHJiUAIjI3VTWidaFyg8OSAJL9nyMAOiBo20ogmUxmc0KtjUi0yj0q8RMxmqYVq9SsTRabU6BSBAJ%2Bf1eX3xIJ84I0kMk0LsqjhV1kGWarWEWAAHqpMjk8uwrN98Xp%2BmTRPiPHEjMdJCAFktVKt1ptIjtiHzJELQXoBYFyo5JU06nhkANUEImpg2Uo9ljWu0uuoMrjVKcPHcHV1UMt8RBvgBKBFIyUAekDkgA6u50KhJEJUHNmJlpAA2Awx83sJQEbjJyTCakIdzLVCiUSoADuwmAkmWzBE3hNDH6O2Qmnj7jwy0krb2heIwEwUKjSi8khN7gI%2BaEA1eQkr5eLOeGuUkmknuzWxBAuuOwekvF4a5I0rTmAzeBNGRUyHbhoN549knNtkNhFECkkWGWLdE1XQ78wn%2BYb9jVNSlZhId9UEwEYYzmMI6mQBA83cZtRGQQC3l/Uc%2BF4AEtyONAQMfPYaVhJYIB9F0/wA79/QlY4CLNC1iKKUjMggEi6SWPhE24iiZFdD8v0za48OAxjLWpFjOLYhioSk%2BleMowTAOEp5Dno%2BtqiYySYWkzAIGFUVTgo1M2XTTN1MlI5pXpOU1g2LZlT5dVyVibhyjOUo7i1Oijncip7kqQKRKRVF0XeWQKWmWYdNpBS5GtEBWXNTlslyfIrD0MV9lE/VvCNWSiKZbFbW6UqnUogxaPch4QuRIwwteDEEuZHE7TmPopyGEZxjc4xCu08ZeETSQ%2BwIVQ8DRUQIFs%2BUHKVXYrE63r9GG6kTMgsyTzmfzROIftWEnAgAXOS5qsC0KXjeBpEvKjqiW6sYJgGiTZKetaxomqaIDe2b7MVbZFrkZaHDWggNuPDMcssyR9sKYgjpOi5cnOh5Lqm67MVau7eger4VscF69lOIsDWKIaRs%2BybbAgEmmp8dw/oVRygdkEG3LBiGtqh3aYbhw7qSRs66pqxEGqu5rGmxx17q6/Hns0oq3rpsn3Ap0b%2By%2BmnldJ7xiiZ%2BbAZVYGhVBkbwejTbzOh3zYYOhHBdOlGRYu%2BrGsxlqSpl3G5Z6hXCMG7juI18bqemg2Aack2no5njOctyGdp1Pn7cnRKe1LTRiHQKwVvYoXcj9F20fq54Mcl/5JHxAA1ZGoKiqkSOlDj4simHErggBrNRko5Ll0t5BLcQ9L1a8uBgi%2BwUhRLH3IGAFPrbhuSV4wrWLWIZUS9Varue6EdlUu5DKh/dT0gQgWeoMn6eYclS/56BUS9FaFuuOL6r0fCm7pfan3K9Jf24k9hYDEIoFQEAWxEAomNdiLFc4L1WubLm1tea2zyoaVQ3VdgEAgD0Bo694GP1iDaR0px%2BjYVGCxHM%2B9zQjmHPeeYLB966D3EXZexx%2BYOyplNJaeh2JsKCiXMuX8sZe1/p1f%2BwJAFaQkiA78yh9KQNQNA/sP1NIELkKMBBwcLamRQcnNBBADTIEwcMbBuD8EkUIbhYhbU1BkN3LwShMJqHsjoXMBhTD0AsN4AIlO8NJzcNsLw2I/DUZi3dpLW63sJHEkBFIxeRM/ygIURArwyiQ5qJAmcXWDMNGyC0UQxB60E7cyTuwo46CTFYOIDgvBVh8mFJsdgEhdoHEUKob3dxI4OyMJrN47CfjbacMCZrMOITsBhPfp/JqEVoniLxvEgEBN%2BqK20nIsBij0kqJwSrPWY44GaO0fHPR20bbb2MaYzItSLENKsUcoprT7HkL3M44oXSWAeN6V4nxQzJQjJDlrMEwM%2BHg3CTMj2UsxHdFiY9ABiS1myMwCk8BSidmwJhNYs2OjkFnNQRc/KVzzH1LkI0hBTynQvKcZ0mhbJumeP6b82i/zU6AvGSC0JHdUCnH0uDIZoskQ7lGAAeTuMK6UABlBALBRDoCEGATgUIEB4BGDsYqrR9pRB5aofayxdg8m6DIAAYsaxwO5hV7B2AQaoZAcxTUiHkH8nZ2gzjOFnPAmh8BGkiVBakUZzQaDSHMb4CrxySFSFoCINqzUhnNEG18pqUQSzmT/bovxfYx3FKvV1HFMB2AiEIHa/BXSJU1dytQur9XH0ZBs1JW9jj9wNeoFirQxp8j4eqkAcjTq5z4RRP0MM%2BJuRFkiQRkgdx5F/IkZIqR0iNvyM2zFo6k3lwips6dasG4xQ4h6TBvhgBCEwOgTkRAtB9g/uLVdDR11JEwKKUYuhF4Qm3VJXdFw8AHqPSekgmhz0JTSk2puIB7kFIfs0rK%2BLnVr02ZRed7BF12BfocqFrR32fuPU0H9fZ1CYmHssAyE9%2BhoZjPhh9k9tHvxHUYHcPRYwcB%2BB2JQqxJAICGMuakCjfBNGXKIJgfwZW/guEwFjmgeXLknOW4gJZPVVnAuOOoLH9UROTdehRG7M2OGzZWHdyw90fsPRh09v7DXFo4yodTOm9Poe/WehkK0X4KIvYGAAVK53UznJAAHE8A8snJoJk0V4ZjgUeJ38OgMgAfyD0yQLNiANkkKWdwmdC1%2BoWMwHwgmqw1lmGeIQ7mRzzCoMinae4xrRr3HmBTYcHWFpGP5nlcXcvRazAYRKbbsxaZ6csTIcx3XjijYafLK5fz7WEDay0mtmxNFwocZzgZlNXqsDeiIYx%2BjLfcBK56cSus9b0sesruxzlMkuTUnBpUPQGSHbVEteGIASp9FSgAsgtK0kX0iRl9TBVxN56hoGIPtGKpVZNWlAlCBRYAwCDOZcdwlp2IH7pI5dl0/EeP6Yu/dp7L2ItH3e5BaCsZvvNl%2ByQAHvWEcFrmD2ALjdweQ9YReo4O5PP9jM%2B4e8eB0BslDYhWLW4fXf2hfaDnbIJhHE673e0KP1vY4HgUFtwGpJ5pq8JWQwv%2BibdsZs6HW4mcs49N1vXHZhfc5iy9vnKnREUrmML0XMPDSdozNndsumvkG5wXxAxkokmWeI1%2BzDtmcNyA19gSQrwFCfN2sFCp46QwirFdKO4UYohYAdmgNEDM4sjlPGEXESYDBh4j9mVAhXiv0o7OORmwgs4xBNTDHc3wsAXFfHmFV4bUBjcO/gZYHZ9roBmL6og7HZIrl6/vFvIwUKiBDiMYQvgDMzdtjuMow4XXpES8ufaEE16jcLbsCbcwpsEH6N8CC8rFUt6EJ3BLyEVzOtCMmImLXUt5AYKwMcrHjqiR3AACTLJgBr/Qq%2B7gBew4re/mJEzWD%2BrGKoAArBUDAQ8NmHCDeMWAoERmPqxiMBoD5h6lPsIIQLgZ0LeH5mPq3oeg1suMgOwGYugDfIviGIQBFpECMDkIQO4LUKvPMMUIPitkYp3NBvmMuOgOgPtF8HOFPmqqgNnriL%2BIPv5sPoWgvkGCGEYLxlGPJkqq3mQQTv0v%2BMIEegsJgKxqcGeHsO2CcMNpIBKq4pgAYVnMAZoOHsOGnqkN4FwZgHQcoQ6FFtYZYSAb1pvh%2BPgdUM3v4caGiAaO4QvntKyjvuNnDKoIflYG9AhFnJIM5nwtxHBnLjCK2v2FYDbqEv4T6BRAALR2wd7ED76JFDAq4pHQHpGZHDTFHa6uw64hjYAiCaBKCv6zIjD649Yb6EAIADZGiWFxF74JFJHqT86W52JC6c624S4q6FEh4eafRKDt677EAGTpElJvSQZHAAoTFVFTG1EFG0qB6q6LGxCNGhInHVFJEfANEZGhIWx8BlA7b5FyCrHkR/JeRixHCzGexW45g3Hij4TqLLEFHgl7EbFbE2pZLcajB7EWwHGe4cKxGYCVGPHnEfBQmXErGwmvGTIPFnFNDJHqKpF7Akn8K7ifEDHfHXEi6hIlGtFCLGBDhcGGibgzEW4gnzHW7glbjQk/GwnBwwIok4piTlIxEBLpHwmVEwksmTLcRgp1R%2BRtF8mLYCk4yrEimEnKlZQHEfSqIokmlIIylHZHGsrOaKnbFGmhJqn/ECr1RAn8koaClgkqkGkHxEkqm7hxyUxmmBnSnonR4Apco8oQB2maybFKlikqkQDOkultFR5iyODPpzASiQZjbLjQ7LDSZzDzDQ6RjMDuHvjhJUZ5lwTCDkRHYSiaD%2BT8D9AwEAgGDLD9CJjtmiwalfHjT0j7b9jRpyBGCAFvY5GIYK6Yo/GFr9CFmoB1D9BlnuEOC3EHYqg6jpnqQbkAhtpyBVShKaB8S8AVCmZVI1EUmznCSTK7n7myC0B8LHn/EAp3lMmHmTLHmoycAPaiBcAwGcCkBCBcAGCAWoBcCRSnkfEZAsBsChACC0CAUEAgU/kPadwgAwEGAAjJgGAwF7i0AACc/AvAtAtAAALAABykB/mcBkWAXAWcCgWkDgWcCAUMAgAGCkDIWMU/mkBwCwBIAuEZ7kCUBCV2AbiDAzj8CYWkDLA%2BA2rsUQCqDKUGCUAPbzAoWkBp4U7CpCCviaX4Ck4%2BZQSaUd40VMVUDcjEAKBcD8AAg4SIXUV5DADjh0CkATanDCol6zCUDKWqCqXkROUziuX0AeVeVFY%2BVKUqWUBUAACKuQ1lxFtAuFFFJQyVAgFFiYiYJQBgw0MBaVlA%2BAKQYeXAqFQVLlSAtAJRXFxAk0KFD2UhdYpoXApRWI/EyAHxHx5FkgpRwqvAbFsF7AdAv5/59FmlLFbImVpRiYZFXUrqdlMBkgEAuAhA4Epg9Akgsg6wSgGeu4/AVVSF9VaFIAZFBFAI/ABFBFZFJQJQFFBg2VFFFFeF1FXAdFQF41pVjAHFXFR1L1nA/V71PFzFn13FoF1VDW7QJoJ1QAA%3D%3D%3D)

**Comment by apolukhin** [comment]
This looks very good. I'll fix some other issues and come back to your pull request.

Try to fox the tests untill then (make a member template function `get` accept an additional `size_t_<I>` parameter. This will remove the need in `template` and `<I>` in `.template get<I>`. This may bypass the compiler related issues).

**Comment by cbeck88** [comment]
It looks like there are still some issues, binding rvalues to non-const references in `make_flat_tuple_of_references`... I must have changed something subtle by accident. Also the enum test is not passing, but I remember that I changed `cast_to_layout_compatible` to a `static_cast` in the enum handling, so maybe that was an incorrect change.

**Comment by cbeck88** [comment]
Hmm -- I can't see a way to avoid using `cast_to_layout_compatible` with enums.

Do you think it's okay to just return a reference to the enum? So that `make_tuple_of_references` would contain references to the enum and not the underlying type.

I guess that this breaks compatibility with previous behavior, but I don't see a way to get a reference to the underlying type without breaking strict aliasing. Gonna think about it some more

**Comment by cbeck88** [comment]
I figured out why it doesn't compile on msvc. It looks to me like there is some problem with the msvc `std::aligned_storage` which causes it not to be default constructible, or something like this. When I use a naive definition, it seems to compile and optimize completely [for all compilers](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSBnVAV2OUxAHIBSAJgGY8AO2QAbZlgDU3fgGECATwAOmAPoFiAQ0IMZ2bgAYAgn0EjxUmfOZLRmPYZMDhYiZmlzmBPKMIKHxqYuFu5WALaYYST%2B/PqBxkKaEQxKmuySDJgAjsyYImoENnbSAOwAQo6OBJG2mtUesgwE6CAgDHgAXgWSAHKkkmKaDAySACoBRk3EzMgEkgBGQ2oAZsSoYaoRYfOYxKUVxpJHY5IAbpri9vwHJiUAIjI3VTWidaFyg8OSAJL9nyMAOiBo20ogmUxmc0KtjUi0yj0q8RMxmqYVq9SsTRabU6BSBAJ%2Bf1eX3xIJ84I0kMk0LsqjhV1kGWarWEWAAHqpMjk8uwrN98Xp%2BmTRPiPHEjMdJCAFktVKt1ptIjtiHzJELQXoBYFyo5JU06nhkANUEImpg2Uo9ljWu0uuoMrjVKcPHcHV1UMt8RBvgBKBFIyUAekDkgA6u50KhJEJUHNmJlpAA2Awx83sJQEbjJyTCakIdzLVCiUSoADuwmAkmWzBE3hNDH6O2Qmnj7jwy0krb2heIwEwUKjSi8khN7gI%2BaEA1eQkr5eLOeGuUkmknuzWxBAuuOwekvF4a5I0rTmAzeBNGRUyHbhoN549knNtkNhFECkkWGWLdE1XQ78wn%2BYb9jVNSlZhId9UEwEYYzmMI6mQBA83cZtRGQQC3l/Uc%2BF4AEtyONAQMfPYaVhJYIB9F0/wA79/QlY4CLNC1iKKUjMggEi6SWPhE24iiZFdD8v0za48OAxjLWpFjOLYhioSk%2BleMowTAOEp5Dno%2BtqiYySYWkzAIGFUVTgo1M2XTTN1MlI5pXpOU1g2LZlT5dVyVibhyjOUo7i1Oijncip7kqQKRKRVF0XeWQKWmWYdNpBS5GtEBWXNTlslyfIrD0MV9lE/VvCNWSiKZbFbW6UqnUogxaPch4QuRIwwteDEEuZHE7TmPopyGEZxjc4xCu08ZeETSQ%2BwIVQ8DRUQIFs%2BUHKVXYrE63r9GG6kTMgsyTzmfzROIftWEnAgAXOS5qsC0KXjeBpEvKjqiW6sYJgGiTZKetaxomqaIDe2b7MVbZFrkZaHDWggNuPDMcssyR9sKYgjpOi5cnOh5Lqm67MVau7eger4VscF69lOIsDWKIaRs%2BybbAgEmmp8dw/oVRygdkEG3LBiGtqh3aYbhw7qSRs66pqxEGqu5rGmxx17q6/Hns0oq3rpsn3Ap0b%2By%2BmnldJ7xiiZ%2BbAZVYGhVBkbwejTbzOh3zYYOhHBdOlGRYu%2BrGsxlqSpl3G5Z6hXCMG7juI18bqemg2Aack2no5njOctyGdp1Pn7cnRKe1LTRiHQKwVvYoXcj9F20fq54Mcl/5JHxAA1ZGoKiqkSOlDj4simHErggBrNRko5Ll0t5BLcQ9L1a8uBgi%2BwUhRLH3IGAFPrbhuSV4wrGUE342LWIZUS9Varue6EdlUu5DKh/dT0gQgWeoMn6eYclG/56BBw6pX9oZ3XjgQHitTbaJre5EpRfyAbtV2koAEkXYixIOw0%2BL8AEv%2BIStEIGK20lAt6JFFKb2UjREWMNIEsWvnXZ%2BBJjIJ25hZW21kQGnHxH6GGYCS6i3wW7CWEVbre06pXUk/txJ7CwGIRQKgIAtiIBRMa0CYS5wXqtc2XNra81tnlQ0qhuq7AIBAHoDQt4yJfrEG0jpTj9GwqMFiOYj7mhHMOe88wWBH10HuIuy9jj8wdlTKaS09DsWcUFZhKJ2E3Wlu1H2PDgR8K0hJQR35lD6TEagCR/YfqaV0XIUYsjg4W1Moo5OyiCAGmQGo4YGitE6KwWk2Rhi7TGN3LwMxMILHsmsXMWx9j0CON4L4lO8NJweNsF42IPjUZi3dpLThITuHEkBOExeADonCLiV4BJIdkkgTOLrBmqTZDpP0XI9aFCckuKOCowp6jiCaO0VYLZOzcIGLamoGppjzG92aSODsdiaztOwl022bjemazDgM7AQzi4jMCVjL2Ey8bTIBATfqaComYCEbE0RSzEmaJVnrMcMCKm7MyQo7aNs94FKKZkc5pSrnlO2ZU%2B5ToTF7nqcUF5LAWnvLaR0n5ko/khy1mCYG3jwbDPRuFIJkLuiTMerw2ZCKBFIpiSI%2BJ6KpF2D0bcuR%2BKDmEqUcS/KpKSmXLkNcml5VHkMueZYtkrzWmfI5Sg1xqceWAv5YMjuqBTj6XBj80WSIdyjAAPJ3D9dKAAyggFgoh0BCDAJwKECA8AjB2MVVo%2B0ojutUPtZYuweTdBkAAMTzY4Hcfq9g7AINUMgOYpqRDyD%2BTsH9KznGIHgTQ%2BAjSjKgtSKM5oNBpDmN8aN45JCpC0BEcthaQzml7a%2BAtATy4cOCd0X4vsY7ilXp/DimA7ARCEDtBBSaQAprdWoDNWaz6MnmSi3exx%2B7ZvUCxVoY0%2BTeP3dE06udvEUQYbbeB%2BhWE1UkDuPIv5EjJFSOkG9%2BQ73SOFU1Bk4yyr9Hg/aTQDcYoXDwMAIQmB0CciIFoPsRKjjocw0MURFEEJZyZCQTQfZVDcAAKxlF0PR2qTxgp/zBXOhoCyQNq1Q3JXSHo1G%2BEw9h3D1G%2BzVVnSKqwPGkiYFFKMXQi8IQxQ4kJ4jWGcNNAk3BtKt6m4gCpUpjJsRCNrsrAsyiEH2BQbsK0KlmmxM6fw3B4eywDIT36Jpj0nnJ6mbY6xsWO4eixg4D8DsShViSAQEMZc1JYm%2BCaMuUQTA/jht/BcJgMXNDuuXJOI9xASwtqrOBccdQYtZs4zJuQcmIgrscBZreqgNMia0%2BJ1z9pN51exYJ5YwmMPtZczRhkK0HOxKk0YQMAAqWbuppuSAAOJ4HdZOTQTJorwzHLE/Lv4dAZH0/kN5kgWbEAbJIUs7hM47s7QsZgPhMtVhrLMM8Qh5sjnmFQJFO09xjTHXuPMFWw7Vp3SMdb7qzuveO1mAwiVH3Ziax6ZYmQ5hZ0IAgUdhp3srl/PtYQ5bLSa2bE0XChxpuBmq7B7jsTeNjH6D1yQwbnpTLecjzW9IcN/d2IRk5eryWlV86MeBtVXQC488Gn09LeAAFkFpWkO%2BkSMHaYKNJvPUNAxB9oxVKqVq0oEoSxLAGAb5drednM0T5jzQuXSb0txACXUvZdGwO6fRXkFoKxlV82dXJAteo7a9uuYPYNuN0N8bpxk2jg7kW/2BLKhjt4HQGyAdiFTtbnbaKqp3RE9sgmEcJrvcut7oZzZgo96jNSU3SD4Ssgc/9CZ3chZdqtzR9j0jlHCek8p5O3L9P4LPZZ/tDnvPTICn7ozNnds/XWVs80XxXJqC1nqf6057TeGRvqCsA37AkhXgKBZUwu1%2BEUnxMkAtrYqgJ%2BUW4qXuz39H1yGH4MvfLLOXbhDP6wN0o7hRiiFgB2aAaIDMZ2I4p4YQuISYBgL%2BXgMOH2X2MULKx244jMwgWcMQ%2BaMMO43wWAFwr4eY8aQ6qA%2BO3O%2BAywHY%2B06AMwHaRA8WskK4qOR8%2BBIwKEogIcIwwgvgWmpOtsO4ZQw4H86Ql2y4%2B0EEa8eOO6uwhOcwxOBA/Q3wEEUaMa%2BBQgncF2yEK4daoQyYRMsBNBeQDArAY4sWx0okO4AAEmWJgBDohi4O4NAXMAQetiRNDtobFiqIxgxg8NmHCDeMWAoN5owbFiMBoCts2qwcIIQGEZ0LeGtowQQVhhDsuMgOwMUugPfDwSGIQAdpECMDkIQO4LUKvPMMUDQfVvkp3GvMgcuOgOgPtF8HOKwYmqgGAbiL%2BDQetnQTutwUGCGEYKllGOVrGgQfEZ7p8v%2BMINhgsJgLFqcGeHsO2CcDjozo0pgJMVnHYZoPvsOIAakN4MUZgOkT0Q6EdsGrtrvpsYgesVRBEdUHgfYcaGiAaPsdwXtA6uIQTnDKoDIVYG9BRnsNNt4hfhPhRAALR2zEHEBSFfFDA16/FuFn7eLcT2Fv7er1RR4hjYAiCaBKAGGwYjDt6x5o7jiY5GhLHvGSGfHfHqQZ4QqD4OFJ4j6F415P474LafRKBEESHEAGRn77JvTar2o9LglclQnfGP4Wqb6P4MlmYAmDLkmQmUkwk/HwmynAoWx8BlCs4o5WAsnkQomux95ca0m0r0m56LzH5rJMk6nSmsk8ockQmrLJajC8kWz8kL6CkCzymilKkfApJWlSlmmsneJemKlNA/EpJ/EImDLqm8CakEnMk2l6nN4GnGBDjFGGibjUn95SxipD42lbj%2Bm142m7iUxJLOkapulHJ2xCnTbsmcljoBmInDSCpvxeRixHA0kD4mk5j5nqSFksliQ/almaLOn8nxyVmvE1l1kQnWmBkQDcQtkuKomGk1Y5l0k9mBkFkSkJmBklnBySLlnDQVkpIClHDcquruoQC1maz2lcmzlNmJierJnMLsZiyOCqZzASgCn47Lh2rLDFZzDzB2qRjMD7HvjDKsI/lwTCCgLukSgoblD8D9D0YAgGDLD9CJioUsIuLxl6Sc79gNmyBGCIYK5l4wgOY4q147r9D/moB1D9AgX7Gvw75c4qg6ivnqSsUAgP6yBVSDKaB8Sxmby85ilUXCTApcU8W0DeICVv7cqSX9hWB8XAoCWoycCS6iBcD0acCkBCBcAGA6WoBcCRRCWxkZAsBsChACC0A6UED6XqWS6dwgD0YGAAjDSJgAAcAAnB5SUPRrwPRvwB5QACzBWkCaWcDBU6V6WcAGWkBGWcA6UMAgAGCkB2WxXqWkBwCwBIA7HAHkCUB5V2AbhiC0BeWqCJhhXLA%2BDlrJUQCqANUGCUCS7zD2WkDzCoHEAKBcA2WkCAGB5%2BpCCvhtVYBwQzj2YZWkD4B%2B4rZQRtXmhIpeAcCcC9XEERVxVUDchdVcD8BuUAi9V2Azjjh0CkCE6nB%2BqfbfaUANWqBNXkThV5DADHX0BnUXXwF2X1WNWUBUAACKuQXV/AvAtABg9GvlwNAgHliYiYJQBgw09GJQtAlA%2BAKQe%2BXADlD1R1SAtAPokuIRYQ9lGleA8wyVkAkuzRdYpoXAIJWI/EyAGpGptAwVkgIJfqvASVFl7AdAGlWl0VbVCVbIkNIJlVkg0uwa1cjIZVkgvABgtAJQkgAASqMKGJIBALgIQOBKYPQJILIOsEoMAbuPwNjbZQTY5SAMFV5QCCUPwIbTLbwMFSUMFYmLQPDeFVwFFbpXzWjYwClWlSba7ZwGzR7ZNQlcbRlTjaQBDu0CaGbUAA%3D%3Dl)

**Comment by cbeck88** [comment]
I wonder if it makes sense to essentially offer the "precise" reflection interface to C++14 users, based on loophole implementation, and with the `offset_based_getter`? Because then we probably can give a totally `strict-aliasing` friendly implementation, unless I'm missing something. We could leave the flat reflection implementation using the `cast_to_layout_compatible` for structs and enums, since afaik you need to do that for enums anyways.

**Comment by apolukhin** [comment]
Super awesome pstch! Thanks a lot!

**Pull request merged**
